# Generated by Django 4.0.4 on 2022-05-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaupeAchat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LesEquipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modeles', models.CharField(max_length=100)),
                ('marques', models.CharField(max_length=100)),
                ('prix', models.IntegerField()),
                ('poids', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='equipement',
            name='marques',
        ),
        migrations.RemoveField(
            model_name='equipement',
            name='mideles',
        ),
    ]
