# Generated by Django 4.0.4 on 2022-05-14 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TaupeAchat', '0002_lesequipement_remove_equipement_marques_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equipement',
        ),
        migrations.AddField(
            model_name='lesequipement',
            name='typeobjet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TaupeAchat.listeequipement'),
        ),
    ]
