# Generated by Django 4.0.4 on 2022-05-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biblio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('nombre_livre', models.IntegerField()),
            ],
        ),
    ]
