# Generated by Django 4.0.4 on 2022-05-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livre', '0003_livre_bibliotheque'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivreDirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('auteur', models.CharField(max_length=100)),
                ('nombres_pages', models.IntegerField()),
                ('resume', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
