# Generated by Django 4.0.4 on 2022-05-10 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livre', '0004_livredirect'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LivreDirect',
        ),
    ]
